# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
          cache: maven

      - name: Grant execute permission for Maven wrapper
        run: chmod +x mvnw
 
      - name: Build and test with Maven Wrapper
        run: ./mvnw clean verify
 
      - name: SonarQube Analysis
        run: ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Spring-PetClinic -Dsonar.projectName='Spring-PetClinic'

      # This step is optional but shows how you might create an artifact to be used later
      - name: Archive production jar
        uses: actions/upload-artifact@v4
        with:
          name: spring-petclinic-jar
          path: target/spring-petclinic-*.jar