name: SSH Test!

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  ssh-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:

        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}


        - name: Remove any existing app (Kill process on port 8080 on remote host)
          run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "fuser -k 8080/tcp || true"
    
        - name: Start Spring PetClinic # this runs in detached mode, you have to verify if it's running in the server.
          run: ssh -n -f -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "\
            nohup java -jar /home/ubuntu/spring-petclinic-*.jar > /dev/null 2>&1 &"
